In [9]:
import json
import numpy as np
from pathlib import Path

from model_ranking import (
    to_target_transfer_correlations,
    correlation_table,
    load_transfer_metric_results,
    avg_correlation_table,
    avg_correlation_to_latex,
    avg_correlation_to_latex_transposed,
)

### Mitochondria

In [10]:
performance_path_mito = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/transfer_performance_scores.json"
with open(performance_path_mito, "r") as f:
    performance_scores_mito = json.load(f)["performance_scores"]

# Gauss EI

### Mitochondria

In [11]:
base_path = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/consistency/direct/EI_consistency/CMB"
#selected_augmentations = ["a001-a003", "a003-a005", "a005-a007", "a007-a01", "a01-a012", "a012-a015", "a015-a02"]
selected_augmentations = ["a01-a012"]
for aug in selected_augmentations:
    file_name = f"transfer_Gauss_{aug}_CMB_05f_05b_EI_scores.json"
    consistency_path = Path(base_path) / file_name
    results = load_transfer_metric_results(consistency_path)
    consistency_scores = results["transfer_scores"]
    targets = list(consistency_scores.keys())
    print(aug)
    KT_scores, SP_scores, PE_scores = to_target_transfer_correlations(
        targets=targets,
        transfer_metric_per_target=consistency_scores,
        performance_per_target=performance_scores_mito,
        )
    df_mito_gauss_EI = correlation_table(KT_scores, SP_scores, PE_scores, targets=targets)
    df_avg_mito_gauss_EI = avg_correlation_table(df_mito_gauss_EI)
    print(df_avg_mito_gauss_EI)
    print(df_mito_gauss_EI)

Loaded Transfer metric results from: /g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/consistency/direct/EI_consistency/CMB/transfer_Gauss_a01-a012_CMB_05f_05b_EI_scores.json
a01-a012
      KT_avg    KT_std  SR_avg    SR_std  PR_avg    PR_std
Task
Mito   0.765  0.141067   0.855  0.141774  0.8275  0.068496
                kt  kt pval  s rho  s rho pval    pr  pr pval
Task targets
Mito EPFL     0.87     0.00   0.95        0.00  0.91      0.0
     Hmito    0.73     0.00   0.87        0.00  0.80      0.0
     Rmito    0.88     0.00   0.95        0.00  0.85      0.0
     VNC      0.58     0.01   0.65        0.03  0.75      0.0

# Gauss NHD

### Mitochondria

In [12]:
base_path = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/consistency/direct/NHD_consistency"
selected_augmentations = ["a012-a015"]

for aug in selected_augmentations:
    file_name = f"transfer_Gauss_{aug}_CMB_05f_05b_NHD_scores.json"
    consistency_path = Path(base_path) / file_name
    results = load_transfer_metric_results(consistency_path)
    consistency_scores = results["transfer_scores"]
    targets = list(consistency_scores.keys())
    print(aug)
    KT_scores, SP_scores, PE_scores = to_target_transfer_correlations(
        targets=targets,
        transfer_metric_per_target=consistency_scores,
        performance_per_target=performance_scores_mito,
        invert_transfer_metric=True,
        )
    df_mito_gauss_NHD = correlation_table(KT_scores, SP_scores, PE_scores, targets=targets)
    df_avg_mito_gauss_NHD = avg_correlation_table(df_mito_gauss_NHD)
    print(df_avg_mito_gauss_NHD)
    print(df_mito_gauss_NHD)

Loaded Transfer metric results from: /g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/consistency/direct/NHD_consistency/transfer_Gauss_a012-a015_CMB_05f_05b_NHD_scores.json
a012-a015
      KT_avg    KT_std  SR_avg    SR_std  PR_avg    PR_std
Task
Mito  0.7075  0.114419  0.8275  0.134505   0.785  0.086987
                kt  kt pval  s rho  s rho pval    pr  pr pval
Task targets
Mito EPFL     0.81     0.00   0.93        0.00  0.91      0.0
     Hmito    0.70     0.00   0.82        0.00  0.75      0.0
     Rmito    0.77     0.00   0.92        0.00  0.71      0.0
     VNC      0.55     0.03   0.64        0.05  0.77      0.0

# DropOut EI

### Mitochondria

In [13]:
base_path = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/feature_perturbation_consistency/direct/EI_consistency"
selected_augmentations = ["a003"]

for aug in selected_augmentations:
    file_name = f"transfer_DO_{aug}_AllLayers_CMB_05f_05b_EI_scores.json"
    consistency_path = Path(base_path) / file_name
    results = load_transfer_metric_results(consistency_path)
    consistency_scores = results["consistency_scores"]
    targets = list(consistency_scores.keys())
    print(aug)
    KT_scores, SP_scores, PE_scores = to_target_transfer_correlations(
        targets=targets,
        transfer_metric_per_target=consistency_scores,
        performance_per_target=performance_scores_mito,
        )
    df_mito_DO_EI = correlation_table(KT_scores, SP_scores, PE_scores, targets=targets)
    df_avg_mito_DO_EI = avg_correlation_table(df_mito_DO_EI)
    print(df_avg_mito_DO_EI)
    print(df_mito_DO_EI)

Loaded Transfer metric results from: /g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/feature_perturbation_consistency/direct/EI_consistency/transfer_DO_a003_AllLayers_CMB_05f_05b_EI_scores.json
a003
      KT_avg    KT_std  SR_avg    SR_std  PR_avg    PR_std
Task
Mito  0.7275  0.104682  0.8625  0.086554   0.865  0.092556
                kt  kt pval  s rho  s rho pval    pr  pr pval
Task targets
Mito EPFL     0.85      0.0   0.96        0.00  0.95      0.0
     Hmito    0.68      0.0   0.83        0.00  0.79      0.0
     Rmito    0.77      0.0   0.90        0.00  0.94      0.0
     VNC      0.61      0.0   0.76        0.01  0.78      0.0

# DropOut NHD

### Mitochondria

In [14]:
base_path = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/feature_perturbation_consistency/direct/NHD_consistency"
selected_augmentations = ["a003"]

for aug in selected_augmentations:
    file_name = f"transfer_DO_{aug}_AllLayers_CMB_05f_05b_NHD_scores.json"
    consistency_path = Path(base_path) / file_name
    results = load_transfer_metric_results(consistency_path)
    consistency_scores = results["transfer_scores"]
    targets = list(consistency_scores.keys())
    print(aug)
    KT_scores, SP_scores, PE_scores = to_target_transfer_correlations(
        targets=targets,
        transfer_metric_per_target=consistency_scores,
        performance_per_target=performance_scores_mito,
        invert_transfer_metric=True,
        )
    df_mito_DO_NHD = correlation_table(KT_scores, SP_scores, PE_scores, targets=targets)
    df_avg_mito_DO_NHD = avg_correlation_table(df_mito_DO_NHD)
    print(df_avg_mito_DO_NHD)
    print(df_mito_DO_NHD)

Loaded Transfer metric results from: /g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/feature_perturbation_consistency/direct/NHD_consistency/transfer_DO_a003_AllLayers_CMB_05f_05b_NHD_scores.json
a003
      KT_avg    KT_std  SR_avg    SR_std  PR_avg    PR_std
Task
Mito    0.69  0.085245  0.8525  0.073655    0.84  0.096264
                kt  kt pval  s rho  s rho pval    pr  pr pval
Task targets
Mito EPFL     0.81     0.00   0.94         0.0  0.96      0.0
     Hmito    0.62     0.00   0.77         0.0  0.74      0.0
     Rmito    0.69     0.00   0.88         0.0  0.87      0.0
     VNC      0.64     0.01   0.82         0.0  0.79      0.0

# transfer metrics

In [15]:
transfer_metric_abbrevs = {
    "Transfer_Score": "TS",
    "LEEP": "LEEP",
    "NCTI": "NCTI",
    "LogME": "LogME",
    "Hscore": "Hscore",
    "GBC": "GBC",
    "Regularized_Hscore": "RegHscore",
    "Gaussian_LEEP": "NLEEP",
    "NuNo": "NuNo",
    "Dispersion": "Disp",
}

### Mitochondria

In [16]:
base_path = "/g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2"
result_paths = Path(base_path).glob("*.json")


transfer_metric_names_mito = []
transfer_metrics_avg_dfs_mito = []
transfer_metrics_dfs_mito = []
for result_path in result_paths:
    results = load_transfer_metric_results(result_path)
    correlation_scores = results["correlation_scores"]
    idx = 0
    per_target_KT = np.array(correlation_scores["KT"])
    per_target_SP = np.array(correlation_scores["SP"])
    per_target_PE = np.array(correlation_scores["PE"])
    df = correlation_table(per_target_KT, per_target_SP, per_target_PE, targets = ["EPFL", "Hmito", "Rmito", "VNC"])
    transfer_metric_name = '_'.join(result_path.stem.split("_")[1:])
    transfer_metric_abbrev = transfer_metric_abbrevs[transfer_metric_name]
    transfer_metric_names_mito.append(transfer_metric_abbrev)
    df_avg = avg_correlation_table(df)
    transfer_metrics_avg_dfs_mito.append(df_avg)
    transfer_metrics_dfs_mito.append(df)

Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_Gaussian_LEEP.json
Experiment: mitochondria_Gaussian_LEEP
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_GBC.json
Experiment: mitochondria_GBC
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_Hscore.json
Experiment: mitochondria_Hscore
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_LEEP.json
Experiment: mitochondria_LEEP
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_LogME.json
Experiment: mitochondria_LogME
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_NCTI.json
Experiment: mitochondria_NCTI
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_Regularized_Hscore.json
Experiment: mitochondria_Regularized_Hscore
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_Transfer_Score.json
Experiment: mitochondria_Transfer_Score
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_Dispersion.json
Experiment: mitochondria_Dispersion
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57
Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/direct_transfer_results2/mitochondria_NuNo.json
Experiment: mitochondria_NuNo
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57

In [17]:
transfer_metrics_dfs_mito

[                kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL     0.26     0.21   0.32        0.23  0.26     0.34
      Hmito    0.77     0.00   0.90        0.00  0.66     0.01
      Rmito    0.65     0.00   0.82        0.00  0.63     0.01
      VNC     -0.06     0.86  -0.06        0.92 -0.01     0.97,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL     0.45     0.02   0.60        0.01  0.65     0.01
      Hmito    0.43     0.04   0.54        0.04  0.54     0.04
      Rmito    0.34     0.09   0.51        0.06  0.47     0.08
      VNC      0.33     0.15   0.41        0.17  0.23     0.48,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL    -0.12     0.58  -0.21        0.46  0.00     1.00
      Hmito    0.33     0.10   0.50        0.05  0.49     0.07
      Rmito    0.36     0.06   0.53        0.04  0.46     0.08
      VNC      0.36     0.11   0.50        0.09  0.54     0.07,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL     0.79      0.0   0.89         0.0  0.96      0.0
      Hmito    0.90      0.0   0.98         0.0  0.96      0.0
      Rmito    0.94      0.0   0.98         0.0  0.98      0.0
      VNC      0.91      0.0   0.98         0.0  0.98      0.0,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL    -0.24     0.23  -0.33        0.23 -0.30     0.27
      Hmito    0.10     0.61   0.17        0.56  0.05     0.85
      Rmito    0.25     0.22   0.32        0.24  0.09     0.75
      VNC      0.21     0.39   0.25        0.43  0.41     0.18,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL    -0.05     0.85  -0.07        0.75  0.07     0.81
      Hmito    0.30     0.14   0.42        0.12  0.42     0.12
      Rmito    0.27     0.16   0.35        0.23  0.42     0.12
      VNC      0.33     0.13   0.44        0.17  0.58     0.05,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL    -0.12     0.52  -0.21        0.44  0.00     1.00
      Hmito    0.31     0.12   0.49        0.06  0.48     0.07
      Rmito    0.40     0.03   0.58        0.04  0.46     0.08
      VNC      0.36     0.10   0.50        0.11  0.54     0.07,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL     0.54     0.01   0.72        0.01  0.60     0.02
      Hmito    0.28     0.14   0.33        0.23  0.19     0.50
      Rmito    0.08     0.77   0.02        0.94  0.14     0.62
      VNC      0.09     0.74   0.11        0.70  0.00     0.99,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL     0.03     0.94   0.05        0.87 -0.07     0.81
      Hmito   -0.07     0.76  -0.12        0.66 -0.25     0.36
      Rmito   -0.06     0.73  -0.12        0.66 -0.20     0.49
      VNC      0.00     1.00  -0.08        0.81 -0.17     0.60,
                 kt  kt pval  s rho  s rho pval    pr  pr pval
 Task targets
 Mito EPFL     0.49     0.01   0.67        0.01  0.52     0.05
      Hmito    0.20     0.28   0.20        0.51  0.10     0.71
      Rmito    0.06     0.85  -0.03        0.92 -0.05     0.86
      VNC     -0.06     0.87  -0.03        0.90 -0.04     0.90]

# Performance Estimation

## Nuclear Norm

### Mitochondria

In [18]:
base_path = "/g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/NuNo"
result_path = list(Path(base_path).glob("*.json"))

assert len(result_path) == 1, "Expected exactly one result file for NuNo transfer metric"


results = load_transfer_metric_results(result_path[0])
correlation_scores = results["correlation_scores"]
idx = 0
per_target_KT = np.array(correlation_scores["KT"])
per_target_SP = np.array(correlation_scores["SP"])
per_target_PE = np.array(correlation_scores["PE"])
df_NuNo_mito = correlation_table(per_target_KT, per_target_SP, per_target_PE, targets = ["EPFL", "Hmito", "Rmito", "VNC"], num_sig_fig=3)
metric_abbrev = transfer_metric_abbrevs["NuNo"]
df_NuNo_mito_avg = avg_correlation_table(df_NuNo_mito)

Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/NuNo/mitochondria_NuNo.json
Experiment: mitochondria_NuNo
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57

## Dispersion

#### Mitochondria

In [19]:
base_path = "/g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/Dispersion"
result_path = list(Path(base_path).glob("*.json"))

assert len(result_path) == 1, "Expected exactly one result file for Dispersion transfer metric"


results = load_transfer_metric_results(result_path[0])
correlation_scores = results["correlation_scores"]
idx = 0
per_target_KT = np.array(correlation_scores["KT"])
per_target_SP = np.array(correlation_scores["SP"])
per_target_PE = np.array(correlation_scores["PE"])
df_Disp_mito = correlation_table(
    per_target_KT, 
    per_target_SP, 
    per_target_PE, 
    targets = ["EPFL", "Hmito", "Rmito", "VNC"],
    num_sig_fig=4
)
metric_abbrev = transfer_metric_abbrevs["Dispersion"]
df_Disp_mito_avg = avg_correlation_table(df_Disp_mito)

Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/Dispersion/mitochondria_Dispersion.json
Experiment: mitochondria_Dispersion
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57

In [20]:
df_Disp_mito

                  kt  kt pval   s rho  s rho pval      pr  pr pval
Task targets
Mito EPFL     0.0286   0.9391  0.0500      0.8691 -0.0678   0.8103
     Hmito   -0.0667   0.7572 -0.1250      0.6593 -0.2523   0.3643
     Rmito   -0.0574   0.7293 -0.1180      0.6613 -0.1954   0.4853
     VNC      0.0000   1.0000 -0.0769      0.8092 -0.1672   0.6035

# CCFV scores

### Mitochondria

In [21]:
performance_path = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/ccfv/direct/transfer_performance_F1_scores.json"
with open(performance_path, "r") as f:
    ccfv_mito_performance_scores = json.load(f)["performance_scores"]

In [22]:
base_path = "/g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/ccfv/direct"

file_name = f"transfer_CCFV_scores.json"
consistency_path = Path(base_path) / file_name
results = load_transfer_metric_results(consistency_path)
consistency_scores = results["transfer_scores"]
targets = list(consistency_scores.keys())
KT_scores, SP_scores, PE_scores = to_target_transfer_correlations(
    targets=targets,
    transfer_metric_per_target=consistency_scores,
    performance_per_target=ccfv_mito_performance_scores,
    )
df_mito_ccfv = correlation_table(KT_scores, SP_scores, PE_scores, targets=targets)
df_avg_mito_ccfv = avg_correlation_table(df_mito_ccfv)
print(df_avg_mito_ccfv)

Loaded Transfer metric results from: /g/kreshuk/talks/consistency_results/patch_segmentation/mitochondria/transfer_results/ccfv/direct/transfer_CCFV_scores.json
      KT_avg    KT_std  SR_avg    SR_std  PR_avg    PR_std
Task
Mito -0.1125  0.107819   -0.16  0.132916   -0.18  0.111355

# Combined Results

In [23]:
transfer_metric_names_mito

['NLEEP',
 'GBC',
 'Hscore',
 'LEEP',
 'LogME',
 'NCTI',
 'RegHscore',
 'TS',
 'Disp',
 'NuNo']

In [24]:
avg_dataframes = [
    df_avg_mito_gauss_EI,
    df_avg_mito_gauss_NHD,
    df_avg_mito_DO_EI,
    df_avg_mito_DO_NHD,
    # df_NuNo_mito_avg,
    # df_Disp_mito_avg,
    df_avg_mito_ccfv,
    transfer_metrics_avg_dfs_mito
]

In [25]:
import numpy as np
import pandas as pd

dataframes = [
    df_mito_gauss_EI,
    df_mito_gauss_NHD,
    df_mito_DO_EI,
    df_mito_DO_NHD,
    # df_NuNo_mito,
    # df_Disp_mito,
    # df_mito_ccfv,
    transfer_metrics_dfs_mito[7:],
]

avg_dataframes = [
    df_avg_mito_gauss_EI,
    df_avg_mito_gauss_NHD,
    df_avg_mito_DO_EI,
    df_avg_mito_DO_NHD,
    # df_NuNo_mito_avg,
    # df_Disp_mito_avg,
    # df_avg_mito_ccfv,
    transfer_metrics_avg_dfs_mito[7:],
]

metric_names = [
    "Gauss_EI",
    "Gauss_NHD",
    "DO_EI",
    "DO_NHD",
    # "NuNo",
    # "Dispersion",
    # "CCFV",
] + transfer_metric_names_mito[7:]

# Flatten the nested lists of dataframes so each metric lines up with one score df and one avg df
flat_dataframes = dataframes[:-1] + list(dataframes[-1])
flat_avg_dataframes = avg_dataframes[:-1] + list(avg_dataframes[-1])

if len(flat_dataframes) != len(metric_names):
    raise ValueError(
        f"Length mismatch: {len(flat_dataframes)} dataframes vs {len(metric_names)} metric names"
    )

if len(flat_avg_dataframes) != len(metric_names):
    raise ValueError(
        f"Length mismatch: {len(flat_avg_dataframes)} avg dataframes vs {len(metric_names)} metric names"
    )

target_columns = ["EPFL", "Hmito", "Rmito", "VNC"]
corr_specs = [
    ("kt", "kt pval", "KT_avg", "KT_std"),
    ("s rho", "s rho pval", "SR_avg", "SR_std"),
    ("pr", "pr pval", "PR_avg", "PR_std"),
]

combined_rows = []

for metric_name, df_metric, df_metric_avg in zip(metric_names, flat_dataframes, flat_avg_dataframes):
    df_reset = df_metric.reset_index()

    for corr_type, pval_col, avg_col, std_col in corr_specs:
        corr_row = {
            "metric_name": metric_name,
            "corr_type": corr_type,
            "pval_type": "score",
            "corr_avg": df_metric_avg[avg_col].iloc[0],
            "corr_std": df_metric_avg[std_col].iloc[0],
        }
        pval_row = {
            "metric_name": metric_name,
            "corr_type": corr_type,
            "pval_type": "pval",
            "corr_avg": np.nan,
            "corr_std": np.nan,
        }

        for target in target_columns:
            target_match = df_reset[df_reset["targets"] == target]
            if target_match.empty:
                corr_row[target] = np.nan
                pval_row[target] = np.nan
            else:
                corr_row[target] = target_match[corr_type].iloc[0]
                pval_row[target] = target_match[pval_col].iloc[0]

        combined_rows.append(corr_row)
        combined_rows.append(pval_row)

combined_results_df = pd.DataFrame(combined_rows)

sort_orders = {
    "kt": 0,
    "s rho": 1,
    "pr": 2,
    "score": 0,
    "pval": 1,
}

combined_results_df = combined_results_df.sort_values(
    by=["metric_name", "corr_type", "pval_type"],
    key=lambda s: s.map(sort_orders).fillna(s),
).reset_index(drop=True)

combined_results_df

,metric_name,corr_type,pval_type,corr_avg,corr_std,EPFL,Hmito,Rmito,VNC
0,DO_EI,kt,score,0.7275,0.104682,0.85,0.68,0.77,0.61
1,DO_EI,kt,pval,NaN,NaN,0.00,0.00,0.00,0.00
2,DO_EI,s rho,score,0.8625,0.086554,0.96,0.83,0.90,0.76
3,DO_EI,s rho,pval,NaN,NaN,0.00,0.00,0.00,0.01
4,DO_EI,pr,score,0.8650,0.092556,0.95,0.79,0.94,0.78
5,DO_EI,pr,pval,NaN,NaN,0.00,0.00,0.00,0.00
6,DO_NHD,kt,score,0.6900,0.085245,0.81,0.62,0.69,0.64
7,DO_NHD,kt,pval,NaN,NaN,0.00,0.00,0.00,0.01
8,DO_NHD,s rho,score,0.8525,0.073655,0.94,0.77,0.88,0.82
9,DO_NHD,s rho,pval,NaN,NaN,0.00,0.00,0.00,0.00
10,DO_NHD,pr,score,0.8400,0.096264,0.96,0.74,0.87,0.79
11,DO_NHD,pr,pval,NaN,NaN,0.00,0.00,0.00,0.00
12,Disp,kt,score,-0.0250,0.047958,0.03,-0.07,-0.06,0.00
13,Disp,kt,pval,NaN,NaN,0.94,0.76,0.73,1.00
14,Disp,s rho,score,-0.0675,0.080571,0.05,-0.12,-0.12,-0.08
15,Disp,s rho,pval,NaN,NaN,0.87,0.66,0.66,0.81
16,Disp,pr,score,-0.1725,0.075884,-0.07,-0.25,-0.20,-0.17
17,Disp,pr,pval,NaN,NaN,0.81,0.36,0.49,0.60
18,Gauss_EI,kt,score,0.7650,0.141067,0.87,0.73,0.88,0.58
19,Gauss_EI,kt,pval,NaN,NaN,0.00,0.00,0.00,0.01
20,Gauss_EI,s rho,score,0.8550,0.141774,0.95,0.87,0.95,0.65
21,Gauss_EI,s rho,pval,NaN,NaN,0.00,0.00,0.00,0.03
22,Gauss_EI,pr,score,0.8275,0.068496,0.91,0.80,0.85,0.75
23,Gauss_EI,pr,pval,NaN,NaN,0.00,0.00,0.00,0.00
24,Gauss_NHD,kt,score,0.7075,0.114419,0.81,0.70,0.77,0.55
25,Gauss_NHD,kt,pval,NaN,NaN,0.00,0.00,0.00,0.03
26,Gauss_NHD,s rho,score,0.8275,0.134505,0.93,0.82,0.92,0.64
27,Gauss_NHD,s rho,pval,NaN,NaN,0.00,0.00,0.00,0.05
28,Gauss_NHD,pr,score,0.7850,0.086987,0.91,0.75,0.71,0.77
29,Gauss_NHD,pr,pval,NaN,NaN,0.00,0.00,0.00,0.00
30,NuNo,kt,score,0.1725,0.236837,0.49,0.20,0.06,-0.06
31,NuNo,kt,pval,NaN,NaN,0.01,0.28,0.85,0.87
32,NuNo,s rho,score,0.2025,0.329987,0.67,0.20,-0.03,-0.03
33,NuNo,s rho,pval,NaN,NaN,0.01,0.51,0.92,0.90
34,NuNo,pr,score,0.1325,0.267255,0.52,0.10,-0.05,-0.04
35,NuNo,pr,pval,NaN,NaN,0.05,0.71,0.86,0.90
36,TS,kt,score,0.2475,0.215619,0.54,0.28,0.08,0.09
37,TS,kt,pval,NaN,NaN,0.01,0.14,0.77,0.74
38,TS,s rho,score,0.2950,0.311823,0.72,0.33,0.02,0.11
39,TS,s rho,pval,NaN,NaN,0.01,0.23,0.94,0.70
40,TS,pr,score,0.2325,0.257860,0.60,0.19,0.14,0.00
41,TS,pr,pval,NaN,NaN,0.02,0.50,0.62,0.99

In [26]:
from pathlib import Path

output_csv_path = Path("/g/kreshuk/talks/model_ranking/notebooks/thesis/semantic_mito_unsupervised_avg_correlations.csv")
combined_results_df.to_csv(output_csv_path, index=False)
print(f"Saved combined results to: {output_csv_path}")

Saved combined results to: /g/kreshuk/talks/model_ranking/notebooks/thesis/semantic_mito_unsupervised_avg_correlations.csv

# Latex avg table

In [39]:
avg_dfs = [
    df_avg_mito_gauss_EI,
    df_avg_mito_gauss_NHD,
    df_avg_mito_DO_EI,
    df_avg_mito_DO_NHD,
    df_avg_nuclei_gauss_EI,
    df_avg_nuclei_gauss_NHD,
    df_avg_nuclei_DO_EI,
    df_avg_nuclei_DO_NHD,
    df_avg_mito_ccfv,
    df_avg_nuclei_ccfv,
] + transfer_metrics_dfs_mito + transfer_metrics_dfs_nuclei
metric_names = [
    "CTE-EI",
    "CTE-NHD",
    "CTE-EI",
    "CTE-NHD",
    "CTE-EI",
    "CTE-NHD",
    "CTE-EI",
    "CTE-NHD",
    "CCFV",
    "CCFV",
] + transfer_metric_names_mito + transfer_metric_names_nuclei
metric_specs = [
    "Gauss",
    "Gauss",
    "DropOut",
    "DropOut",
    "Gauss",
    "Gauss",
    "DropOut",
    "DropOut",
    "",
    "",
] + [""]*(len(transfer_metric_names_mito)) + [""]*(len(transfer_metric_names_nuclei))

latex_table = avg_correlation_to_latex(
    df_avg_list=avg_dfs,
    metric_name_list=metric_names,
    metric_spec_list=metric_specs,
)
print(latex_table)

\begin{table}[htbp]
    \centering
    \small
    \setlength{\tabcolsep}{3pt}
    \begin{tabular}{cc|ccc|ccc}
    \hline
    \multirow{2}{*}{Metric} & {} & \multicolumn{3}{c|}{Mito} & \multicolumn{3}{c}{Nuclei} \\
 &  & K$\tau$ & S$\rho$ & P$r$ & K$\tau$ & S$\rho$ & P$r$ \\
\hline
\multirow{2}{*}{\begin{tabular}{@{}c@{}} CTE-EI \\ (Gauss)\end{tabular}} & \textit{Avg.} & 0.77 & 0.85 & 0.83 & 0.62 & 0.77 & 0.98 \\
 & \textit{std.} & ±0.14 & ±0.14 & ±0.07 & ±0.12 & ±0.09 & ±0.03 \\
\hline
\multirow{2}{*}{\begin{tabular}{@{}c@{}} CTE-NHD \\ (Gauss)\end{tabular}} & \textit{Avg.} & 0.71 & 0.83 & 0.79 & 0.69 & 0.82 & 0.97 \\
 & \textit{std.} & ±0.11 & ±0.13 & ±0.09 & ±0.10 & ±0.08 & ±0.04 \\
\hline
\multirow{2}{*}{\begin{tabular}{@{}c@{}} CTE-EI \\ (DropOut)\end{tabular}} & \textit{Avg.} & 0.73 & 0.86 & 0.86 & 0.74 & 0.85 & 0.90 \\
 & \textit{std.} & ±0.10 & ±0.09 & ±0.09 & ±0.16 & ±0.11 & ±0.09 \\
\hline
\multirow{2}{*}{\begin{tabular}{@{}c@{}} CTE-NHD \\ (DropOut)\end{tabular}} & \textit{Avg.} & 0.69 & 0.85 & 0.84 & 0.71 & 0.84 & 0.62 \\
 & \textit{std.} & ±0.09 & ±0.07 & ±0.10 & ±0.16 & ±0.12 & ±0.37 \\
\hline
\multirow{2}{*}{CCFV} & \textit{Avg.} & -0.11 & -0.16 & -0.18 & -0.03 & -0.05 & -0.16 \\
 & \textit{std.} & ±0.11 & ±0.13 & ±0.11 & ±0.31 & ±0.37 & ±0.52 \\
\hline
\multirow{2}{*}{NLEEP} & \textit{Avg.} & 0.41 & 0.49 & 0.39 & 0.11 & 0.12 & 0.32 \\
 & \textit{std.} & ±0.38 & ±0.45 & ±0.32 & ±0.11 & ±0.11 & ±0.22 \\
\hline
\multirow{2}{*}{GBC} & \textit{Avg.} & 0.39 & 0.52 & 0.47 & -0.13 & -0.16 & -0.08 \\
 & \textit{std.} & ±0.06 & ±0.08 & ±0.18 & ±0.29 & ±0.40 & ±0.39 \\
\hline
\multirow{2}{*}{Hscore} & \textit{Avg.} & 0.23 & 0.33 & 0.37 & 0.29 & 0.25 & 0.31 \\
 & \textit{std.} & ±0.24 & ±0.36 & ±0.25 & ±0.52 & ±0.58 & ±0.36 \\
\hline
\multirow{2}{*}{LEEP} & \textit{Avg.} & 0.89 & 0.96 & 0.97 & 0.67 & 0.77 & 0.94 \\
 & \textit{std.} & ±0.07 & ±0.04 & ±0.01 & ±0.37 & ±0.30 & ±0.01 \\
\hline
\multirow{2}{*}{LogME} & \textit{Avg.} & 0.08 & 0.10 & 0.06 & -0.20 & -0.28 & -0.49 \\
 & \textit{std.} & ±0.22 & ±0.29 & ±0.29 & ±0.26 & ±0.35 & ±0.35 \\
\hline
\multirow{2}{*}{NCTI} & \textit{Avg.} & 0.21 & 0.28 & 0.37 & 0.29 & 0.25 & 0.30 \\
 & \textit{std.} & ±0.18 & ±0.24 & ±0.22 & ±0.52 & ±0.58 & ±0.32 \\
\hline
\multirow{2}{*}{RegHscore} & \textit{Avg.} & 0.24 & 0.34 & 0.37 & 0.35 & 0.36 & 0.34 \\
 & \textit{std.} & ±0.24 & ±0.37 & ±0.25 & ±0.37 & ±0.43 & ±0.34 \\
\hline
\multirow{2}{*}{TS} & \textit{Avg.} & 0.25 & 0.30 & 0.23 & 0.02 & 0.10 & -0.09 \\
 & \textit{std.} & ±0.22 & ±0.31 & ±0.26 & ±0.28 & ±0.39 & ±0.38 \\
\hline
\end{tabular}
\caption{Correlation scores for multiple metrics}
\label{tab:multiple_metrics}
\end{table}

# Test Transposed Table Format

In [40]:
# Test the transposed format with the same data
latex_table_transposed = avg_correlation_to_latex_transposed(
    df_avg_list=avg_dfs,
    metric_name_list=metric_names,
    metric_spec_list=metric_specs,
)
print(latex_table_transposed)

\begin{table*}[htbp]
    \centering
    \setlength{\tabcolsep}{1.5pt}
    \begin{tabular}{cc|cc|cc|cc|cc|cc|cc|cc|cc|cc|cc|cc|cc|cc}
    \hline
    \multirow{2}{*}{Task} &  & \multicolumn{2}{c|}{\begin{tabular}{@{}c@{}} CTE-EI \\ (Gauss)\end{tabular}} & \multicolumn{2}{c|}{\begin{tabular}{@{}c@{}} CTE-NHD \\ (Gauss)\end{tabular}} & \multicolumn{2}{c|}{\begin{tabular}{@{}c@{}} CTE-EI \\ (DropOut)\end{tabular}} & \multicolumn{2}{c|}{\begin{tabular}{@{}c@{}} CTE-NHD \\ (DropOut)\end{tabular}} & \multicolumn{2}{c|}{CCFV} & \multicolumn{2}{c|}{NLEEP} & \multicolumn{2}{c|}{GBC} & \multicolumn{2}{c|}{Hscore} & \multicolumn{2}{c|}{LEEP} & \multicolumn{2}{c|}{LogME} & \multicolumn{2}{c|}{NCTI} & \multicolumn{2}{c|}{RegHscore} & \multicolumn{2}{c}{TS} \\
 &  & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} \\
\hline
\multirow{3}{*}{\rotatebox[origin=c]{90}{Mito}} & K$\tau$ & 0.77 & ±0.1 & 0.71 & ±0.1 & 0.73 & ±0.1 & 0.69 & ±0.1 & -0.11 & ±0.1 & 0.41 & ±0.4 & 0.39 & ±0.1 & 0.23 & ±0.2 & 0.89 & ±0.1 & 0.08 & ±0.2 & 0.21 & ±0.2 & 0.24 & ±0.2 & 0.25 & ±0.2 \\
 & S$\rho$ & 0.85 & ±0.1 & 0.83 & ±0.1 & 0.86 & ±0.1 & 0.85 & ±0.1 & -0.16 & ±0.1 & 0.49 & ±0.5 & 0.52 & ±0.1 & 0.33 & ±0.4 & 0.96 & ±0.0 & 0.10 & ±0.3 & 0.28 & ±0.2 & 0.34 & ±0.4 & 0.30 & ±0.3 \\
 & P$r$ & 0.83 & ±0.1 & 0.79 & ±0.1 & 0.86 & ±0.1 & 0.84 & ±0.1 & -0.18 & ±0.1 & 0.39 & ±0.3 & 0.47 & ±0.2 & 0.37 & ±0.3 & 0.97 & ±0.0 & 0.06 & ±0.3 & 0.37 & ±0.2 & 0.37 & ±0.2 & 0.23 & ±0.3 \\
\hline
\multirow{3}{*}{\rotatebox[origin=c]{90}{Nuclei}} & K$\tau$ & 0.62 & ±0.1 & 0.69 & ±0.1 & 0.74 & ±0.2 & 0.71 & ±0.2 & -0.03 & ±0.3 & 0.11 & ±0.1 & -0.13 & ±0.3 & 0.29 & ±0.5 & 0.67 & ±0.4 & -0.20 & ±0.3 & 0.29 & ±0.5 & 0.35 & ±0.4 & 0.02 & ±0.3 \\
 & S$\rho$ & 0.77 & ±0.1 & 0.82 & ±0.1 & 0.85 & ±0.1 & 0.84 & ±0.1 & -0.05 & ±0.4 & 0.12 & ±0.1 & -0.16 & ±0.4 & 0.25 & ±0.6 & 0.77 & ±0.3 & -0.28 & ±0.3 & 0.25 & ±0.6 & 0.36 & ±0.4 & 0.10 & ±0.4 \\
 & P$r$ & 0.98 & ±0.0 & 0.97 & ±0.0 & 0.90 & ±0.1 & 0.62 & ±0.4 & -0.16 & ±0.5 & 0.32 & ±0.2 & -0.08 & ±0.4 & 0.31 & ±0.4 & 0.94 & ±0.0 & -0.49 & ±0.3 & 0.30 & ±0.3 & 0.34 & ±0.3 & -0.09 & ±0.4 \\
\hline
\end{tabular}
\caption{Correlation scores for multiple metrics (transposed)}
\label{tab:multiple_metrics_transposed}
\end{table*}

In [20]:
transfer_metric_abbrevs = {
    "Transfer_Score": "TS",
    "LEEP": "LEEP",
    "NCTI": "NCTI",
    "LogME": "LogME",
    "Hscore": "Hscore",
    "GBC": "GBC",
    "Regularized_Hscore": "RegHscore",
    "Gaussian_LEEP": "NLEEP",
    "NuNo": "NuNo",
    "Dispersion": "Dispersion",
}

In [26]:
from typing import List
import pandas as pd

# NuNo

In [ ]:
base_path = "/g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/NuNo"
result_paths = Path(base_path).glob("*.json")

NuNo_names_mito = []
NuNo_dfs_mito: List[pd.DataFrame] = []
for result_path in result_paths:
    results = load_transfer_metric_results(result_path)
    correlation_scores = results["correlation_scores"]
    idx = 0
    per_target_KT = np.array(correlation_scores["KT"])
    per_target_SP = np.array(correlation_scores["SP"])
    per_target_PE = np.array(correlation_scores["PE"])
    df = correlation_table(per_target_KT, per_target_SP, per_target_PE, targets = ["EPFL", "Hmito", "Rmito", "VNC"])
    transfer_metric_name = '_'.join(result_path.stem.split("_")[1:])
    transfer_metric_abbrev = transfer_metric_abbrevs[transfer_metric_name]
    NuNo_names_mito.append(transfer_metric_abbrev)
    df_avg = avg_correlation_table(df)
    NuNo_dfs_mito.append(df_avg)

Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/NuNo/mitochondria_NuNo.json
Experiment: mitochondria_NuNo
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57

# Dispersion

In [ ]:
base_path = "/g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/Dispersion"
result_paths = Path(base_path).glob("*.json")

Dispersion_names_mito = []
Dispersion_dfs_mito: List[pd.DataFrame] = []
for result_path in result_paths:
    results = load_transfer_metric_results(result_path)
    correlation_scores = results["correlation_scores"]
    idx = 0
    per_target_KT = np.array(correlation_scores["KT"])
    per_target_SP = np.array(correlation_scores["SP"])
    per_target_PE = np.array(correlation_scores["PE"])
    df = correlation_table(per_target_KT, per_target_SP, per_target_PE, targets = ["EPFL", "Hmito", "Rmito", "VNC"])
    transfer_metric_name = '_'.join(result_path.stem.split("_")[1:])
    transfer_metric_abbrev = transfer_metric_abbrevs[transfer_metric_name]
    Dispersion_names_mito.append(transfer_metric_abbrev)
    df_avg = avg_correlation_table(df)
    Dispersion_dfs_mito.append(df_avg)

Loaded Transfer metric results from: /g/kreshuk/talks/sampled_features/semantic_segmentation/mitochondria/1k_pixels_sampled/transfer_metric_results/Dispersion/mitochondria_Dispersion.json
Experiment: mitochondria_Dispersion
Targets: 4 (EPFL, Hmito, Rmito, VNC)
Source models: 15
Total transfers: 57

In [27]:
avg_dfs = [
    df_avg_mito_DO_EI,
    NuNo_dfs_mito[0],
    Dispersion_dfs_mito[0],
]
metric_names = [
    "CTE-EI",
    "NuNo",
    "Dispersion",
]
metric_specs = [
    "DropOut",
    "",
    "",
]

latex_table = avg_correlation_to_latex(
    df_avg_list=avg_dfs,
    metric_name_list=metric_names,
    metric_spec_list=metric_specs,
)
print(latex_table)

\begin{table}[htbp]
    \centering
    \small
    \setlength{\tabcolsep}{3pt}
    \begin{tabular}{cc|ccc}
    \hline
    \multirow{2}{*}{Metric} & {} & \multicolumn{3}{c}{Mito} \\
 &  & K$\tau$ & S$\rho$ & P$r$ \\
\hline
\multirow{2}{*}{\begin{tabular}{@{}c@{}} CTE-EI \\ (DropOut)\end{tabular}} & \textit{Avg.} & 0.73 & 0.86 & 0.86 \\
 & \textit{std.} & ±0.10 & ±0.09 & ±0.09 \\
\hline
\multirow{2}{*}{NuNo} & \textit{Avg.} & 0.17 & 0.20 & 0.13 \\
 & \textit{std.} & ±0.24 & ±0.33 & ±0.27 \\
\hline
\multirow{2}{*}{Dispersion} & \textit{Avg.} & -0.03 & -0.07 & -0.17 \\
 & \textit{std.} & ±0.05 & ±0.08 & ±0.08 \\
\hline
\end{tabular}
\caption{Correlation scores for multiple metrics}
\label{tab:multiple_metrics}
\end{table}

In [28]:
# Test the transposed format with the same data
latex_table_transposed = avg_correlation_to_latex_transposed(
    df_avg_list=avg_dfs,
    metric_name_list=metric_names,
    metric_spec_list=metric_specs,
)
print(latex_table_transposed)

\begin{table*}[htbp]
    \centering
    \setlength{\tabcolsep}{1.5pt}
    \begin{tabular}{cc|cc|cc|cc}
    \hline
    \multirow{2}{*}{Task} &  & \multicolumn{2}{c|}{\begin{tabular}{@{}c@{}} CTE-EI \\ (DropOut)\end{tabular}} & \multicolumn{2}{c|}{NuNo} & \multicolumn{2}{c}{Dispersion} \\
 &  & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} & \textit{Avg.} & \textit{std.} \\
\hline
\multirow{3}{*}{\rotatebox[origin=c]{90}{Mito}} & K$\tau$ & 0.73 & ±0.1 & 0.17 & ±0.2 & -0.03 & ±0.0 \\
 & S$\rho$ & 0.86 & ±0.1 & 0.20 & ±0.3 & -0.07 & ±0.1 \\
 & P$r$ & 0.86 & ±0.1 & 0.13 & ±0.3 & -0.17 & ±0.1 \\
\hline
\end{tabular}
\caption{Correlation scores for multiple metrics (transposed)}
\label{tab:multiple_metrics_transposed}
\end{table*}